# org: tince250
app: cloud-drive
service: cloud-drive
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: eu-central-1
  memorySize: 128
  timeout: 10
  environment:
    TABLE_NAME:
      Ref: fileMetadataTable
    FOLDER_TABLE_NAME:
      Ref: folderMetadataTable
    BUCKET_NAME:
      Ref: fileUploadBucket
    # FILE_UPDATED_TOPIC:
    #   Ref: FileUpdatedTopic
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem
        - dynamodb:Scan
      Resource:
        - "Fn::GetAtt": [fileMetadataTable, Arn]
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem
        - dynamodb:Scan
      Resource:
        - "Fn::GetAtt": [folderMetadataTable, Arn]
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
        - s3:ListBucket
        - s3:DeleteObject
      Resource:
        - "Fn::Join": ["", ["arn:aws:s3:::", "cloud-drive-storage-tsn2", "/*"]]
    - Effect: Allow
      Action:
        - s3:ListBucket
      Resource:
        - "Fn::GetAtt": [fileUploadBucket, Arn]
    - Effect: Allow
      Action:
        - cognito-idp:ListUsers
      Resource: 
        - "*"
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: 
        - "*"
    - Effect: Allow
      Action:
        - ses:SendEmail
      Resource: 
        - "*"
    - Effect: Allow
      Action:
        - sns:Publish
      Resource:
        - "*"

        


package:
  individually: true
  patterns:
    - '!**/**'
    - 'utility/**'

functions:
  uploadFile:
    handler: file-upload/upload-file.handler
    package:
      include: 'file-upload/**'
    events:
      - http:
          path: file
          method: post
          cors: true
          authorizer:
            name: MyAuthorizer
            type: COGNITO_USER_POOLS
            arn:
              Fn::GetAtt:
                - CognitoUserPool
                - Arn

  uploadMetadata:
    handler: metadata-upload/upload-metadata.handler
    package:
      include: 'metadata-upload/**'
    environment:
      FILE_UPDATED_TOPIC: !Ref FileUpdatedTopic
    events:
      - http:
          path: metadata
          method: post
          cors: true
          authorizer:
            name: MyAuthorizer
            type: COGNITO_USER_POOLS
            arn:
              Fn::GetAtt:
                - CognitoUserPool
                - Arn

  uploadFolderMetadata:
    handler: metadata-folder-upload/upload-metadata-folder.handler
    package:
      include: 'metadata-folder-upload/**'
    events:
      - http:
          path: metadata-folder
          method: post
          cors: true
          authorizer:
            name: MyAuthorizer
            type: COGNITO_USER_POOLS
            arn:
              Fn::GetAtt:
                - CognitoUserPool
                - Arn

  readContent:
    handler: read-content/read-content.handler
    package:
      include: 'read-content/**'
    events:
      - http:
          path: folder
          method: get
          cors: true
          authorizer:
            name: MyAuthorizer
            type: COGNITO_USER_POOLS
            arn:
              Fn::GetAtt:
                - CognitoUserPool
                - Arn
  createFolder:
    handler: create-folder/create-folder.handler
    package:
      include: 'create-folder/**'
    events:
      - http:
          path: folder
          method: post
          cors: true
          authorizer:
            name: MyAuthorizer
            type: COGNITO_USER_POOLS
            arn:
              Fn::GetAtt:
                - CognitoUserPool
                - Arn

  createFile:
    handler: create-file/create-file.handler
    package:
      include: 'create-file/**'
    events:
      - http:
          path: create-file
          method: post
          cors: true
          authorizer:
            name: MyAuthorizer
            type: COGNITO_USER_POOLS
            arn:
              Fn::GetAtt:
                - CognitoUserPool
                - Arn
  
  deleteFolder:
    handler: delete-folder/delete-folder.handler
    package:
      include: 'delete-folder/**'
    events:
      - http:
          path: folder
          method: delete
          cors: true
          authorizer:
            name: MyAuthorizer
            type: COGNITO_USER_POOLS
            arn:
              Fn::GetAtt:
                - CognitoUserPool
                - Arn

  updateFile:
    handler: update-file/update-file.handler
    package:
      include: 'update-file/**'
    events:
      - http:
          path: update-file
          method: post
          cors: true
          authorizer:
            name: MyAuthorizer
            type: COGNITO_USER_POOLS
            arn:
              Fn::GetAtt:
                - CognitoUserPool
                - Arn                
                
  deleteFile:
    handler: delete-file/delete-file.handler
    package:
      include: 'delete-file/**'
    environment:
      FILE_DELETED_TOPIC: !Ref FileDeletedTopic
    events:
      - http:
          path: file
          method: delete
          cors: true
          authorizer:
            name: MyAuthorizer
            type: COGNITO_USER_POOLS
            arn:
              Fn::GetAtt:
                - CognitoUserPool
                - Arn
                
  readFileDetails:
    handler: read-file-details/read-file-details.handler
    package:
      include: 'read-file-details/**'
    events:
      - http:
          path: file
          method: get
          cors: true
          authorizer:
            name: MyAuthorizer
            type: COGNITO_USER_POOLS
            arn:
              Fn::GetAtt:
                - CognitoUserPool
                - Arn

  readFolderDetails:
    handler: read-folder-details/read-folder-details.handler
    package:
      include: 'read-folder-details/**'
    events:
      - http:
          path: folder-metadata
          method: get
          cors: true
          authorizer:
            name: MyAuthorizer
            type: COGNITO_USER_POOLS
            arn:
              Fn::GetAtt:
                - CognitoUserPool
                - Arn

  downloadFile:
    handler: file-download/download-file.handler
    package:
      include: 'file-download/**'
    events:
      - http:
          path: file-download
          method: get
          cors: true
          authorizer:
            name: MyAuthorizer
            type: COGNITO_USER_POOLS
            arn:
              Fn::GetAtt:
                - CognitoUserPool
                - Arn

  getUserByUsername:
    handler: get-user-by-username/get-user-by-username.handler
    package:
      include: 'get-user-by-username/**'
    events:
      - http:
          path: user
          method: get
          cors: true
          authorizer:
            name: MyAuthorizer
            type: COGNITO_USER_POOLS
            arn:
              Fn::GetAtt:
                - CognitoUserPool
                - Arn
  
  getSharedFilesByUsername:
    handler: get-shared-files/get-shared-files.handler
    package:
      include: 'get-shared-files/**'
    events:
      - http:
          path: shared-files
          method: get
          cors: true
          authorizer:
            name: MyAuthorizer
            type: COGNITO_USER_POOLS
            arn:
              Fn::GetAtt:
                - CognitoUserPool
                - Arn

  sendNotificationForFile:
    handler: send-notification-for-file/send-notification-for-file.handler
    package:
      include: 'send-notification-for-file/**'
    events:
      - sns:
          arn: !Ref FileUpdatedTopic
          topicName: FileUpdatedTopicName
      - sns:
          arn: !Ref FileDeletedTopic
          topicName: FileDeletedTopicName

  

resources:
  Parameters:
    EmailSES:
      Type: String
      Default: arn:aws:ses:eu-central-1:953661704071:identity/vujadinovic01@gmail.com

  Resources:
    CognitoUserPool:
      Type: 'AWS::Cognito::UserPool'
      Properties:
        UserPoolName: cloud-drive-user-pool-2
        EmailConfiguration:
            EmailSendingAccount: DEVELOPER
            From: TSNDrive <vujadinovic01@gmail.com>
            SourceArn:
              Ref: EmailSES

    UserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: cloud-drive-user-pool-client-2
        GenerateSecret: false
        UserPoolId: { Ref: CognitoUserPool }
        AccessTokenValidity: 5
        IdTokenValidity: 5
        ExplicitAuthFlows:
          - "ADMIN_NO_SRP_AUTH"

    fileUploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: cloud-drive-storage-tsn2

    fileMetadataTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: cloud-drive-db-tsn
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    
    folderMetadataTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: cloud-drive-folder-db-tsn
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    
    FileUpdatedTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: FileUpdatedTopicName

    FileDeletedTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: FileDeletedTopicName
